// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxmWSFUbVnWG5YjSpAI0MeLDdgePFWKU',
    appId: '1:230343352269:web:5fa826619b60063576ee84',
    messagingSenderId: '230343352269',
    projectId: 'hymn-book-690dd',
    authDomain: 'hymn-book-690dd.firebaseapp.com',
    storageBucket: 'hymn-book-690dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHxmWSFUbVnWG5YjSpAI0MeLDdgePFWKU',
    appId: '1:230343352269:android:5fa826619b60063576ee84',
    messagingSenderId: '230343352269',
    projectId: 'hymn-book-690dd',
    storageBucket: 'hymn-book-690dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHxmWSFUbVnWG5YjSpAI0MeLDdgePFWKU',
    appId: '1:230343352269:ios:5fa826619b60063576ee84',
    messagingSenderId: '230343352269',
    projectId: 'hymn-book-690dd',
    storageBucket: 'hymn-book-690dd.firebasestorage.app',
    iosBundleId: 'com.hymnestry.hymn_book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHxmWSFUbVnWG5YjSpAI0MeLDdgePFWKU',
    appId: '1:230343352269:ios:5fa826619b60063576ee84',
    messagingSenderId: '230343352269',
    projectId: 'hymn-book-690dd',
    storageBucket: 'hymn-book-690dd.firebasestorage.app',
    iosBundleId: 'com.hymnestry.hymn_book',
  );
}
